stages:
  - build
  - test

worker_build:
  stage: build
  image: 
    name: golang:1.15.2
  script:
    - make

docker_build:
  stage: build
  image:
    name: gitlab/dind
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker build -f ./build/Dockerfile -t ${DOCKER_TEAM}/raptor-worker .
    - docker push ${DOCKER_TEAM}/raptor-worker
  only:
     refs:
      - master
      - dev
